"""Rolling handoff briefs for OPEN agent sessions.

Unlike ``session_summaries`` (closed-session, generated by a background
worker) or ``project_briefs`` (per-repo synthesis), an active brief is a
TTL-cached snapshot computed lazily on demand. The MCP tool calls
``generate_active_brief`` every time a peer agent asks for a handoff —
the function returns the cached row if it's still fresh, otherwise it
regenerates from the session's most recent events.

No background thread: freshness is controlled purely by ``max_age_seconds``.
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

import duckdb

from drover.event_identity import canonical_agent_events_cte
from drover.server.briefs.active_prompt import build_active_brief_prompt
from drover.server.summarizer.backends import (
    BackendError,
    LLMBackend,
    SummarizerBackendConfig,
    select_backend,
)

log = logging.getLogger("drover.briefs.active")

_RECENT_EVENTS = 30
_BRIEF_COLUMNS = (
    "session_id",
    "brief_md",
    "last_user_req",
    "current_objective",
    "files_touched",
    "open_blockers",
    "suggested_next",
    "events_seen",
    "freshness_ts",
    "generator_model",
)


def _row_to_dict(row: tuple) -> dict:
    out: dict[str, Any] = dict(zip(_BRIEF_COLUMNS, row))
    ts = out.get("freshness_ts")
    if isinstance(ts, datetime):
        out["freshness_ts"] = ts.isoformat()
    files = out.get("files_touched")
    if files is not None:
        out["files_touched"] = list(files)
    return out


def _iso(ts: Any) -> Optional[str]:
    if ts is None:
        return None
    if isinstance(ts, datetime):
        return ts.isoformat()
    return str(ts)


def _fetch_cached(con: duckdb.DuckDBPyConnection, session_id: str) -> Optional[tuple]:
    cols = ", ".join(_BRIEF_COLUMNS)
    return con.execute(
        f"SELECT {cols} FROM active_session_briefs WHERE session_id=?",
        [session_id],
    ).fetchone()


def _is_fresh_sql(
    con: duckdb.DuckDBPyConnection, session_id: str, max_age_seconds: float
) -> bool:
    """Ask DuckDB whether the cached row is within the TTL.

    We compute freshness in SQL so that ``now()`` (the same clock that
    wrote ``freshness_ts``) is used for both sides of the comparison. This
    avoids timezone mismatches between Python's UTC clock and DuckDB's
    naive TIMESTAMP column.
    """
    row = con.execute(
        """SELECT (now() - freshness_ts) <= INTERVAL (?) SECOND
             FROM active_session_briefs WHERE session_id=?""",
        [float(max_age_seconds), session_id],
    ).fetchone()
    return bool(row and row[0])


def generate_active_brief(
    duckdb_path: Path,
    session_id: str,
    *,
    backend: Optional[LLMBackend] = None,
    backend_config: Optional[SummarizerBackendConfig] = None,
    max_age_seconds: float = 60,
) -> dict:
    """Return the rolling handoff brief for ``session_id``.

    Returns the cached row if its ``freshness_ts`` is within
    ``max_age_seconds``. Otherwise re-fetches the last 30 events, calls
    the backend, and upserts the result. Caller passes either an explicit
    ``backend`` (tests) or a ``backend_config`` to resolve one.
    """
    duckdb_path = Path(duckdb_path)

    # Cheap path: cached + fresh.
    con = duckdb.connect(str(duckdb_path))
    try:
        if _is_fresh_sql(con, session_id, max_age_seconds):
            row = _fetch_cached(con, session_id)
            if row is not None:
                return _row_to_dict(row)
    finally:
        con.close()

    resolved_backend = backend
    if resolved_backend is None:
        if backend_config is None:
            raise RuntimeError("active brief: no backend or backend_config supplied")
        try:
            resolved_backend = select_backend(
                job_kind="active_brief", config=backend_config
            )
        except BackendError as e:
            raise RuntimeError(f"active brief backend selection failed: {e}") from e

    # Pull events (newest first → reverse to chronological for the prompt).
    con = duckdb.connect(str(duckdb_path), read_only=True)
    try:
        cur = con.execute(
            f"""WITH {canonical_agent_events_cte()}
               SELECT id, timestamp, agent_id, event_type, role, content
               FROM canonical_agent_events WHERE session_id=?
               ORDER BY timestamp DESC LIMIT ?""",
            [session_id, _RECENT_EVENTS],
        )
        cols = [d[0] for d in cur.description]
        events_desc = [dict(zip(cols, r)) for r in cur.fetchall()]
    finally:
        con.close()

    if not events_desc:
        raise RuntimeError(f"no events for session {session_id}")

    events = list(reversed(events_desc))
    agent_id = events[-1].get("agent_id") or "unknown"

    prompt = build_active_brief_prompt(
        events=[
            {
                "role": e.get("role"),
                "content": e.get("content"),
                "timestamp": _iso(e.get("timestamp")),
                "event_type": e.get("event_type"),
            }
            for e in events
        ],
        session_id=session_id,
        agent_id=agent_id,
        started_at=_iso(events[0].get("timestamp")),
        ended_at=_iso(events[-1].get("timestamp")),
    )

    try:
        llm = resolved_backend.summarize(prompt)
    except BackendError as e:
        raise RuntimeError(str(e)) from e

    files_touched = list(llm.get("files_touched") or [])
    events_seen = len(events)
    generator_model = getattr(resolved_backend, "model", "unknown")

    con = duckdb.connect(str(duckdb_path))
    try:
        con.execute(
            """INSERT OR REPLACE INTO active_session_briefs
               (session_id, brief_md, last_user_req, current_objective,
                files_touched, open_blockers, suggested_next,
                events_seen, freshness_ts, generator_model)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, now(), ?)""",
            [
                session_id,
                llm.get("brief_md") or "",
                llm.get("last_user_req") or "",
                llm.get("current_objective") or "",
                files_touched,
                llm.get("open_blockers") or "",
                llm.get("suggested_next") or "",
                events_seen,
                generator_model,
            ],
        )
        row = _fetch_cached(con, session_id)
    finally:
        con.close()

    if row is None:  # pragma: no cover — INSERT just succeeded
        raise RuntimeError(f"active brief upsert disappeared for {session_id}")
    return _row_to_dict(row)
