import Foundation
import Testing
@testable import DroverKit

// Capability-driven iOS controls (#420). Fixtures:
// - harness-capabilities-v1.json: generated by the server's own test from a
//   real `HarnessDaemonState`, so it is what current hosts publish;
// - harness-capabilities-mixed.json: Claude Code, Codex, agy, DeepSeek, shell,
//   two fixture adapters with unusual mixes, malformed and future rows, a
//   legacy (matrix-less) host, a host with no envelope and a future-schema host.

private func mixedSnapshot() throws -> HarnessSnapshot {
    let url = try #require(droverKitFixtureURL("harness-capabilities-mixed"))
    return try HarnessSnapshot.decode(from: Data(contentsOf: url))
}

private func goldenSnapshot() throws -> HarnessSnapshot {
    let url = try #require(droverKitFixtureURL("harness-capabilities-v1"))
    return try HarnessSnapshot.decode(from: Data(contentsOf: url))
}

private func host(_ id: String, in snapshot: HarnessSnapshot) throws -> HostSummary {
    try #require(snapshot.hosts.first { $0.id == id })
}

private func controls(_ harness: String, on hostID: String = "studio") throws -> HarnessControls {
    HarnessControls(snapshot: try mixedSnapshot(), hostID: hostID, harness: harness)
}

@Suite
struct HarnessCapabilityDecodingTests {
    /// The test-side built-in rows and the mixed fixture must say exactly what
    /// a current host says, or every other test here proves nothing.
    @Test func fixturesMatchTheServerGeneratedEnvelope() throws {
        let golden = try host("test-host", in: goldenSnapshot())
        let studio = try host("studio", in: mixedSnapshot())
        #expect(golden.harnessOffers.map(\.name)
            == ["shell", "claude-code", "codex", "agy", "deepseek-harness"])
        for offer in golden.harnessOffers {
            guard case .v1 = offer.advertisement else {
                Issue.record("\(offer.name) is not a v1 row")
                continue
            }
            #expect(v1Offer(offer.name).capabilities == offer.capabilities, "\(offer.name)")
            #expect(studio.offer(named: offer.name)?.capabilities == offer.capabilities, "\(offer.name)")
        }
    }

    @Test func builtInMatricesDecodeToTheirDeclaredBehaviour() throws {
        let studio = try host("studio", in: mixedSnapshot())
        let claude = try #require(studio.offer(named: "claude-code")).capabilities
        #expect(claude.launchModes == [.structured])
        #expect(claude.approvals && claude.interrupt && claude.nativeResume)
        #expect(claude.modelCatalog && claude.interactiveAuth)
        #expect(!claude.turnPreferences && !claude.worktree)

        let codex = try #require(studio.offer(named: "codex")).capabilities
        #expect(!codex.approvals && codex.worktree && codex.turnPreferences)

        let deepseek = try #require(studio.offer(named: "deepseek-harness")).capabilities
        #expect(!deepseek.interactiveAuth && deepseek.modelCatalog)

        let shell = try #require(studio.offer(named: "shell")).capabilities
        #expect(shell.launchModes == [.pty])
        #expect(shell == HarnessCapabilities(launchModes: [.pty]))
    }

    @Test func unknownAdditiveFieldsAreIgnored() throws {
        let lab = try #require(try host("studio", in: mixedSnapshot()).offer(named: "fixture-lab"))
        #expect(lab.advertisement == .v1(HarnessCapabilities(
            launchModes: [.pty, .structured],
            approvals: true,
            usage: true,
            worktree: true,
            // Advertised true, but there is no catalog to choose from.
            turnPreferences: false,
            attachments: ["image/png"]
        )))
    }

    @Test func missingOptionalFlagsAreFalseAndHarnessIDMayBeOmitted() throws {
        let wildcard = try #require(try host("studio", in: mixedSnapshot()).offer(named: "fixture-wildcard"))
        #expect(wildcard.capabilities == HarnessCapabilities(
            launchModes: [.structured], modelCatalog: true, turnPreferences: true,
            attachments: ["image/*"]
        ))
    }

    @Test func malformedMatricesAdvertiseNothingAndAreNeverLegacy() throws {
        let studio = try host("studio", in: mixedSnapshot())
        for name in ["broken", "mismatched", "stringly"] {
            let offer = try #require(studio.offer(named: name))
            #expect(offer.advertisement == .invalid, "\(name)")
            #expect(offer.capabilities == .none)
            #expect(!offer.isLaunchable)
            #expect(offer.unavailableReason == HarnessCapabilityCopy.invalidMatrix)
        }
    }

    @Test func malformedAttachmentMIMETypesInvalidateTheMatrix() throws {
        let row = HarnessOffer(row: .object([
            "name": .string("fixture"), "enabled": .bool(true),
            "capabilities": .object([
                "schema_version": .number(1),
                "launch_modes": .array([.string("structured")]),
                "attachments": .array([.string("image/jpeg"), .string("not a MIME")])
            ])
        ]))
        #expect(row?.advertisement == .invalid)
        #expect(row?.isLaunchable == false)
    }

    @Test func futureSchemasAreRetainedButNeverInterpreted() throws {
        let studio = try host("studio", in: mixedSnapshot())
        let future = try #require(studio.offer(named: "future-harness"))
        #expect(future.advertisement == .unsupportedSchema(2))
        #expect(future.unavailableReason == HarnessCapabilityCopy.unsupportedSchema(2))

        let futureHost = try host("future-host", in: mixedSnapshot())
        #expect(futureHost.launchableOffers.isEmpty)
        #expect(futureHost.launchUnavailableReason == HarnessCapabilityCopy.unsupportedSchema(2))
    }

    @Test func legacyHostsAreMetadataOnly() throws {
        let old = try host("old-mini", in: mixedSnapshot())
        // The legacy enabled list survives as metadata, unchanged.
        #expect(old.harnesses == ["codex", "codex beta"])
        #expect(old.advertisesCapabilities == false)
        #expect(old.launchableOffers.isEmpty)
        #expect(old.launchUnavailableReason == HarnessCapabilityCopy.legacyHost)
        // String rows and enabled rows explain themselves; a disabled one
        // stays hidden as it always was.
        #expect(old.unavailableOffers.map(\.offer.name) == ["shell", "codex", "codex beta"])
        #expect(old.unavailableOffers.allSatisfy { $0.reason == HarnessCapabilityCopy.legacyHost })
        // No matrix is synthesized from a familiar name.
        #expect(old.offer(named: "codex")?.capabilities == HarnessCapabilities.none)
    }

    @Test func aHostWithoutAnyEnvelopeAdvertisesNothing() throws {
        let bare = try host("bare-nas", in: mixedSnapshot())
        #expect(bare.harnessOffers.isEmpty)
        #expect(bare.launchUnavailableReason == HarnessCapabilityCopy.legacyHost)
    }

    @Test func launchableOrderIsStructuredFirstThenHostOrder() throws {
        let studio = try host("studio", in: mixedSnapshot())
        #expect(studio.launchableOffers.map(\.name) == [
            "claude-code", "codex", "agy", "deepseek-harness",
            "fixture-lab", "fixture-wildcard", "shell",
        ])
        // Advertised but switched off by the host: not launchable, and not
        // worth an explanation either.
        #expect(studio.offer(named: "codex-disabled")?.isLaunchable == false)
        #expect(!studio.unavailableOffers.contains { $0.offer.name == "codex-disabled" })
    }

    @Test func structuredIsPreferredWhenBothModesAreAdvertised() {
        #expect(HarnessCapabilities(launchModes: [.pty, .structured]).preferredLaunchMode == .structured)
        #expect(HarnessCapabilities(launchModes: [.pty]).preferredLaunchMode == .pty)
        #expect(HarnessCapabilities(launchModes: []).preferredLaunchMode == nil)
    }

    @Test func attachmentTypesHonourWildcardsOnly() {
        let png = HarnessCapabilities(launchModes: [.structured], attachments: ["image/png"])
        #expect(png.accepts(mediaType: "image/png"))
        #expect(!png.accepts(mediaType: "image/jpeg"))
        let any = HarnessCapabilities(launchModes: [.structured], attachments: ["image/*"])
        #expect(any.accepts(mediaType: "image/jpeg"))
        #expect(!any.accepts(mediaType: "application/pdf"))
    }
}

@Suite
struct HarnessControlsTests {
    fileprivate struct Expected: Sendable {
        let mode: HarnessLaunchMode?
        let approvals, interrupt, models, midSession, signIn, worktree, images: Bool
    }

    /// One row per materially different capability combination.
    @Test(arguments: [
        ("claude-code", Expected(mode: .structured, approvals: true, interrupt: true, models: true,
                                 midSession: false, signIn: true, worktree: false, images: true)),
        ("codex", Expected(mode: .structured, approvals: false, interrupt: true, models: true,
                           midSession: true, signIn: true, worktree: true, images: true)),
        ("agy", Expected(mode: .structured, approvals: false, interrupt: true, models: true,
                         midSession: true, signIn: true, worktree: true, images: true)),
        ("deepseek-harness", Expected(mode: .structured, approvals: false, interrupt: true, models: true,
                                      midSession: true, signIn: false, worktree: true, images: true)),
        ("shell", Expected(mode: .pty, approvals: false, interrupt: false, models: false,
                           midSession: false, signIn: false, worktree: false, images: false)),
        ("fixture-lab", Expected(mode: .structured, approvals: true, interrupt: false, models: false,
                                 midSession: false, signIn: false, worktree: true, images: false)),
        ("fixture-wildcard", Expected(mode: .structured, approvals: false, interrupt: false, models: true,
                                      midSession: true, signIn: false, worktree: false, images: true)),
    ])
    fileprivate func controlsFollowTheMatrix(_ harness: String, _ expected: Expected) throws {
        let c = try controls(harness)
        #expect(c.launchMode == expected.mode)
        #expect(c.showsApprovals == expected.approvals)
        #expect(c.canInterrupt == expected.interrupt)
        #expect(c.showsModelControls == expected.models)
        #expect(c.canChangePreferencesMidSession == expected.midSession)
        #expect(c.offersSignIn == expected.signIn)
        #expect(c.explainsWorktreeIsolation == expected.worktree)
        #expect(c.acceptsImageAttachments == expected.images)
        #expect((c.interruptUnavailableReason == nil) == expected.interrupt)
        #expect((c.approvalsUnavailableReason == nil) == expected.approvals)
    }

    @Test func withheldControlsExplainThemselves() throws {
        let lab = try controls("fixture-lab")
        #expect(lab.interruptUnavailableReason == HarnessCapabilityCopy.interruptUnsupported)
        #expect(lab.attachmentsUnavailableReason == HarnessCapabilityCopy.attachmentsUnsupported)
        #expect(try controls("codex").approvalsUnavailableReason == HarnessCapabilityCopy.approvalsUnsupported)
        #expect(try controls("claude-code").preferencesLockedReason == HarnessCapabilityCopy.preferencesLocked)
    }

    @Test func legacyHostsWithholdEverythingAndSaySo() throws {
        let legacy = try controls("codex", on: "old-mini")
        #expect(legacy.launchMode == nil)
        #expect(!legacy.canInterrupt && !legacy.showsApprovals && !legacy.showsModelControls)
        #expect(!legacy.offersSignIn && !legacy.acceptsImageAttachments && !legacy.supportsNativeResume)
        #expect(legacy.interruptUnavailableReason == HarnessCapabilityCopy.legacyHost)
        #expect(legacy.approvalsUnavailableReason == HarnessCapabilityCopy.legacyHost)
    }

    @Test func unresolvedAndMissingRowsFailClosed() throws {
        let unresolved = HarnessControls.unresolved
        #expect(unresolved.launchMode == nil && !unresolved.canInterrupt && !unresolved.showsApprovals)
        #expect(unresolved.interruptUnavailableReason == HarnessCapabilityCopy.checking)

        let missing = try controls("removed-harness")
        #expect(missing.isResolved && missing.offer == nil)
        #expect(!missing.canInterrupt)
        #expect(missing.interruptUnavailableReason == HarnessCapabilityCopy.missingFromSnapshot)
        #expect(try controls("codex", on: "nowhere").offer == nil)
    }
}

extension MockNetworkTests {
@Suite(.serialized)
struct CapabilityDrivenLaunchTests {
    let mock = MockNetwork()
    private func client() -> DroverClient { mock.client() }

    private func store() -> HarnessModelCatalogStore {
        HarnessModelCatalogStore(defaults: UserDefaults(suiteName: "cap-launch-\(UUID().uuidString)")!)
    }

    @MainActor private func launchModel() throws -> LaunchModel {
        LaunchModel(client: client(), snapshot: try mixedSnapshot(), store: store())
    }

    @Test @MainActor func defaultsComeFromTheEnvelopeNotAName() throws {
        let model = try launchModel()
        #expect(model.hostID == "studio")
        // First structured-capable launchable row in host order.
        #expect(model.harness == "claude-code")
        #expect(model.availableHarnesses.last == "shell")
        #expect(!model.availableHarnesses.contains("broken"))
        #expect(model.unavailableHarnesses.map(\.name) == ["future-harness", "broken", "mismatched", "stringly"])
    }

    @Test @MainActor func launchSheetControlsFollowTheSelection() throws {
        let model = try launchModel()
        #expect(model.isStructured && model.supportsInteractiveAuth)
        #expect(model.showsRunPreferences && model.canAttachImages)
        #expect(model.runPreferences.isCatalogAvailable)

        model.harness = "fixture-lab"
        #expect(model.isStructured)
        #expect(!model.supportsInteractiveAuth)
        #expect(!model.showsRunPreferences)
        #expect(!model.canAttachImages)
        #expect(model.runPreferences.isCatalogAvailable == false)
        #expect(model.controls.explainsWorktreeIsolation)

        model.harness = "deepseek-harness"
        #expect(!model.supportsInteractiveAuth && model.showsRunPreferences)

        model.harness = "shell"
        #expect(!model.isStructured && !model.showsRunPreferences && !model.canAttachImages)
        #expect(model.canLaunch)
    }

    @Test @MainActor func aLegacyHostCannotLaunchAndSaysWhy() throws {
        let model = try launchModel()
        model.hostID = "old-mini"
        #expect(model.harness == "")
        #expect(model.availableHarnesses.isEmpty)
        #expect(model.canLaunch == false)
        #expect(model.harnessUnavailableReason == HarnessCapabilityCopy.legacyHost)
        #expect(model.unavailableHarnesses.map(\.name) == ["shell", "codex", "codex beta"])

        // Even forcing a legacy name in never makes it launchable.
        model.harness = "codex"
        #expect(model.canLaunch == false)
        #expect(model.isStructured == false)
        #expect(model.supportsInteractiveAuth == false)
    }

    @Test @MainActor func launchSendsTheAdvertisedModeAndOnlyAdvertisedExtras() async throws {
        let model = try launchModel()
        model.harness = "fixture-lab"
        model.prompt = "go"
        model.promptAttachments = [TurnAttachment(mediaType: "image/jpeg", data: Data([1]))]

        nonisolated(unsafe) var body: [String: Any] = [:]
        mock.handler = { request in
            body = try! JSONSerialization.jsonObject(with: request.bodyStreamData()) as! [String: Any]
            return (201, Data(#"{"session_id": "lab-1", "mode": "structured"}"#.utf8))
        }
        #expect(await model.launch() == "lab-1")
        #expect(body["harness"] as? String == "fixture-lab")
        #expect(body["mode"] as? String == "structured")
        #expect(body["prompt"] as? String == "go")
        // PNG-only harness: the app's JPEG is never sent.
        #expect((body["images"] as? [Any])?.isEmpty ?? true)
        #expect(body["model"] == nil && body["thinking_effort"] == nil)
    }

    @Test @MainActor func launchRefusesWithoutAnAdvertisedMode() async throws {
        let model = try launchModel()
        model.hostID = "old-mini"
        model.harness = "codex"
        mock.handler = { _ in
            Issue.record("a legacy host must not be asked to launch")
            return (500, Data())
        }
        #expect(await model.launch() == nil)
        #expect(model.launchError == HarnessCapabilityCopy.legacyHost)
    }

    /// A refresh that withdraws the selected harness's launch mode must move
    /// the selection, never leave Launch enabled for it.
    @Test @MainActor func aRefreshThatWithdrawsTheSelectionMovesIt() async throws {
        let before = Data("""
        {"hosts": [{"host_id": "mac", "status": "online", "capabilities": {"harnesses": [
          \(v1Row("shell")), \(v1Row("codex")), \(v1Row("agy"))]}}], "sessions": [], "cwd_suggestions": []}
        """.utf8)
        let after = Data("""
        {"hosts": [{"host_id": "mac", "status": "online", "capabilities": {"harnesses": [
          \(v1Row("shell")), \(v1Row("codex")),
          {"name": "agy", "enabled": true, "capabilities": {"schema_version": 2, "launch_modes": []}}]}}],
         "sessions": [], "cwd_suggestions": []}
        """.utf8)
        let model = LaunchModel(client: client(), snapshot: try HarnessSnapshot.decode(from: before), store: store())
        model.harness = "agy"
        #expect(model.canLaunch)

        mock.handler = { _ in (200, after) }
        await model.refreshSnapshot()

        #expect(model.hostID == "mac")
        #expect(model.harness == "codex")
        #expect(model.runPreferences.harness == "codex")
        #expect(model.unavailableHarnesses.map(\.name) == ["agy"])
    }

    /// A refresh that keeps the harness but withdraws one capability turns
    /// exactly that control off, including its model catalog.
    @Test @MainActor func aRefreshThatWithdrawsACapabilityTurnsItsControlOff() async throws {
        let before = Data("""
        {"hosts": [{"host_id": "mac", "status": "online", "capabilities": {"harnesses": [
          \(v1Row("codex"))]}}], "sessions": [], "cwd_suggestions": []}
        """.utf8)
        let after = Data("""
        {"hosts": [{"host_id": "mac", "status": "online", "capabilities": {"harnesses": [
          {"name": "codex", "enabled": true, "capabilities": {"schema_version": 1,
           "launch_modes": ["structured"], "interrupt": true}}]}}], "sessions": [], "cwd_suggestions": []}
        """.utf8)
        let model = LaunchModel(client: client(), snapshot: try HarnessSnapshot.decode(from: before), store: store())
        #expect(model.supportsInteractiveAuth && model.showsRunPreferences && model.canAttachImages)
        #expect(model.runPreferences.isCatalogAvailable)

        mock.handler = { _ in (200, after) }
        await model.refreshSnapshot()

        #expect(model.harness == "codex")
        #expect(model.canLaunch)
        #expect(!model.supportsInteractiveAuth && !model.showsRunPreferences && !model.canAttachImages)
        #expect(model.runPreferences.isCatalogAvailable == false)
        #expect(model.runPreferences.modelOverride == nil)
    }
}

@Suite(.serialized)
struct CapabilityDrivenChatTests {
    let mock = MockNetwork()
    private func client() -> DroverClient { mock.client() }

    private func fixtureData() throws -> Data {
        try Data(contentsOf: try #require(droverKitFixtureURL("harness-capabilities-mixed")))
    }

    @MainActor private func loadedChat(_ sessionID: String, harness: String) async throws -> ChatModel {
        let snapshot = try fixtureData()
        mock.handler = { request in
            request.url?.path == "/harness" ? (200, snapshot) : (404, Data(#"{"error": "none"}"#.utf8))
        }
        let model = ChatModel(
            client: client(), sessionID: sessionID, harness: harness,
            store: HarnessModelCatalogStore(defaults: UserDefaults(suiteName: "cap-chat-\(UUID().uuidString)")!)
        )
        #expect(model.controls == .unresolved)
        await model.loadSessionMetadata()
        return model
    }

    @Test @MainActor func sessionControlsResolveFromTheSessionsHost() async throws {
        let claude = try await loadedChat("s-claude", harness: "claude-code")
        #expect(claude.controls.showsApprovals && claude.controls.canInterrupt)
        #expect(!claude.controls.canChangePreferencesMidSession)
        #expect(claude.runPreferences.isCatalogAvailable)
        // Handoff targets are structured launchers only: never the PTY shell.
        #expect(claude.handoffHarnesses == [
            "claude-code", "codex", "agy", "deepseek-harness", "fixture-lab", "fixture-wildcard",
        ])

        let lab = try await loadedChat("s-lab", harness: "fixture-lab")
        #expect(lab.controls.showsApprovals)
        #expect(!lab.controls.canInterrupt)
        #expect(lab.runPreferences.isCatalogAvailable == false)
    }

    @Test @MainActor func interruptIsRefusedLocallyWhenNotAdvertised() async throws {
        let lab = try await loadedChat("s-lab", harness: "fixture-lab")
        mock.handler = { _ in
            Issue.record("an unadvertised interrupt must not reach the hub")
            return (500, Data())
        }
        await lab.interrupt()
        #expect(lab.hint == HarnessCapabilityCopy.interruptUnsupported)
    }

    @Test @MainActor func attachmentsNeedAnAdvertisedType() async throws {
        let lab = try await loadedChat("s-lab", harness: "fixture-lab")
        let jpeg = TurnAttachment(mediaType: "image/jpeg", data: Data([1]))
        #expect(await lab.addAttachmentIfRecoverable(jpeg) == false)
        #expect(lab.pendingAttachments.isEmpty)
    }

    @Test @MainActor func legacyHostSessionsStayListableButWithholdControls() async throws {
        let legacy = try await loadedChat("s-legacy", harness: "codex")
        #expect(legacy.controls.isResolved)
        #expect(!legacy.controls.canInterrupt && !legacy.controls.showsApprovals)
        #expect(legacy.controls.interruptUnavailableReason == HarnessCapabilityCopy.legacyHost)
        #expect(legacy.handoffHarnesses.isEmpty)
        #expect(legacy.runPreferences.isCatalogAvailable == false)
    }

    @Test @MainActor func withdrawnAttachmentsPreserveDraftAndNeverPost() async throws {
        let model = ChatModel.fixture(client: client())
        model.composerText = "preserve this"
        let jpeg = TurnAttachment(mediaType: "image/jpeg", data: Data([1]))
        model.pendingAttachments = [jpeg]
        model.controls = HarnessControls(offer: HarnessOffer(
            name: "fixture", capabilities: HarnessCapabilities(launchModes: [.structured])
        ))
        mock.handler = { _ in
            Issue.record("withdrawn attachments must not reach the hub")
            return (500, Data())
        }
        await model.sendTurn()
        #expect(model.composerText == "preserve this")
        #expect(model.pendingAttachments == [jpeg])
        #expect(model.pendingTurn == nil)
    }

    @Test @MainActor func unresolvedAndLegacyTurnsAndHandoffsNeverPost() async throws {
        let legacy = try await loadedChat("s-legacy", harness: "codex")
        let unresolved = ChatModel.fixture(client: client())
        unresolved.controls = .unresolved
        mock.handler = { _ in
            Issue.record("unadvertised turns and handoffs must not reach the hub")
            return (500, Data())
        }
        for model in [legacy, unresolved] {
            model.composerText = "preserve this"
            #expect(!model.canSendTurn)
            await model.sendTurn()
            #expect(model.composerText == "preserve this")
            #expect(await model.handOff() == nil)
            #expect(await model.handOff(targetHarness: "fixture-lab") == nil)
        }
    }

    @Test @MainActor func sessionListHandoffRejectsMissingAndWithdrawnTargets() async throws {
        let store = SessionStore(client: client())
        mock.handler = { _ in
            Issue.record("an unresolved handoff must not reach the hub")
            return (500, Data())
        }
        #expect(await store.continueSession("s-claude") == nil)
        mock.handler = { _ in (200, try! fixtureData()) }
        await store.refresh()
        mock.handler = { _ in
            Issue.record("an unadvertised handoff target must not reach the hub")
            return (500, Data())
        }
        #expect(await store.continueSession("s-legacy") == nil)
        #expect(await store.continueSession("s-claude", targetHarness: "shell") == nil)
        #expect(await store.continueSession("s-claude", targetHarness: "removed-harness") == nil)
    }

    @Test @MainActor func approvalAnswersNeedTheCapability() async throws {
        let codex = try await loadedChat("s-codex", harness: "codex")
        codex.ingest(.message(.fixture(
            seq: 5, type: .approvalPrompt, payload: ["request_id": .string("r1")]
        )))
        #expect(codex.pendingApproval != nil)
        mock.handler = { _ in
            Issue.record("an unadvertised approval must not be answered")
            return (500, Data())
        }
        await codex.approve("allow")
        #expect(codex.controls.approvalsUnavailableReason == HarnessCapabilityCopy.approvalsUnsupported)
    }
}
}  // extension MockNetworkTests

/// Grep-style guard: iOS control code must not branch on harness names.
///
/// Every quoted harness ID in app and DroverKit sources fails this test unless
/// the line carries a `harness-name:` justification (display-only or wire
/// parsing, never a control). `HarnessPresentation.swift` maps IDs to display
/// names and icons, and `UITesting/` holds synthetic fixtures; both are exempt.
@Suite
struct NoHarnessNameBranchingTests {
    private static let harnessIDs = [
        "claude-code", "claude", "codex", "agy", "deepseek-harness", "deepseek",
        "shell", "gemini", "openclaw", "hermes",
    ]
    private static let retiredPolicyNames = ["structuredCapableHarnesses", "interactiveAuthHarnesses"]
    private static let exemptFiles: Set<String> = ["HarnessPresentation.swift"]

    private static var appsRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // DroverKitTests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // DroverKit
            .deletingLastPathComponent()  // apps/drover
    }

    private static func sourceFiles() -> [URL] {
        let roots = [
            appsRoot.appendingPathComponent("DroverKit/Sources/DroverKit"),
            appsRoot.appendingPathComponent("Drover"),
        ]
        return roots.flatMap { root -> [URL] in
            let walker = FileManager.default.enumerator(at: root, includingPropertiesForKeys: nil)
            return (walker?.allObjects as? [URL] ?? []).filter {
                $0.pathExtension == "swift" && !$0.path.contains("/UITesting/")
            }
        }
    }

    @Test func iosSourcesAreScanned() {
        let names = Set(Self.sourceFiles().map(\.lastPathComponent))
        #expect(names.contains("LaunchModel.swift"))
        #expect(names.contains("ChatView.swift"))
        #expect(names.contains("LaunchView.swift"))
    }

    @Test func noControlCodeBranchesOnAHarnessName() throws {
        var offenders: [String] = []
        for file in Self.sourceFiles() where !Self.exemptFiles.contains(file.lastPathComponent) {
            let text = try String(contentsOf: file, encoding: .utf8)
            for (index, line) in text.components(separatedBy: .newlines).enumerated() {
                let trimmed = line.trimmingCharacters(in: .whitespaces)
                if trimmed.hasPrefix("//") { continue }
                for name in Self.retiredPolicyNames where line.contains(name) {
                    offenders.append("\(file.lastPathComponent):\(index + 1) uses \(name)")
                }
                guard !line.contains("harness-name:") else { continue }
                for id in Self.harnessIDs where line.contains("\"\(id)\"") {
                    offenders.append("\(file.lastPathComponent):\(index + 1) quotes \"\(id)\"")
                }
            }
        }
        #expect(offenders.isEmpty, "Derive controls from HarnessControls instead:\n\(offenders.joined(separator: "\n"))")
    }
}
