#!/usr/bin/env bash
# install_shipper_linux.sh — install nexus-collect on a Debian-flavored Linux
# host (defaults tuned for the NAS), shipping to the mac-mini lakehouse.
#
# Run on the target host as the Arnab user from inside the nexus repo:
#   cd ~/jenny/nexus
#   bash scripts/install_shipper_linux.sh
#
# Idempotent: re-running upgrades the install in place.
#
# Knobs (override via env):
#   HOST_ID          agent_id for this host's claude_code source (default: nas-claude)
#   NAS_REMOTE_HOST  ssh target on the lakehouse host (default: Arnabs-Mac-mini.local)
#   NAS_REMOTE_USER  user on the lakehouse host       (default: arnabmac)
#   NEXUS_HOME       per-user state dir for the shipper (default: $HOME/.nexus)
#   ENABLE_OPENCLAW  "true" enables the openclaw source  (default: true)
#   ENABLE_TEMPO_RELAY "true" enables the Tempo→OTLP relay (default: false; turn on for the NAS)
#   TEMPO_BASE_URL   Tempo HTTP API base                 (default: http://192.168.1.70:31989)
#   TEMPO_TARGET_OTLP OTLP gRPC target on the lakehouse  (default: Arnabs-Mac-mini.local:4317)
#   TEMPO_SERVICES   comma-separated service.name list   (default: agentweave-proxy,mux-router)

set -euo pipefail
exec > >(tee -a /tmp/nexus-shipper-install.log) 2>&1

echo "==================================================================="
echo "Nexus shipper install (Linux/systemd) — $(date -Iseconds)"
echo "==================================================================="

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
NEXUS_HOME="${NEXUS_HOME:-$HOME/.nexus}"
HOST_ID="${HOST_ID:-nas-claude}"
NAS_REMOTE_HOST="${NAS_REMOTE_HOST:-Arnabs-Mac-mini.local}"
NAS_REMOTE_USER="${NAS_REMOTE_USER:-arnabmac}"
ENABLE_OPENCLAW="${ENABLE_OPENCLAW:-true}"
ENABLE_TEMPO_RELAY="${ENABLE_TEMPO_RELAY:-false}"
TEMPO_BASE_URL="${TEMPO_BASE_URL:-http://192.168.1.70:31989}"
TEMPO_TARGET_OTLP="${TEMPO_TARGET_OTLP:-Arnabs-Mac-mini.local:4317}"
TEMPO_SERVICES="${TEMPO_SERVICES:-agentweave-proxy,mux-router}"

cat <<EOF

REPO_DIR        : $REPO_DIR
NEXUS_HOME      : $NEXUS_HOME
HOST_ID         : $HOST_ID
SHIP TO         : $NAS_REMOTE_USER@$NAS_REMOTE_HOST:~/.nexus/incoming/$HOST_ID/
ENABLE_OPENCLAW : $ENABLE_OPENCLAW
EOF

cd "$REPO_DIR"

# ---------------------------------------------------------------------------
# Step 1 — uv
# ---------------------------------------------------------------------------
echo
echo "=== Step 1: uv ==="
if ! command -v uv >/dev/null 2>&1; then
    echo "uv missing — installing via official script"
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
fi
echo "uv version: $(uv --version)"

# ---------------------------------------------------------------------------
# Step 2 — Python deps
# ---------------------------------------------------------------------------
echo
echo "=== Step 2: uv sync ==="
uv sync --quiet
uv run python -c "import click, pydantic; print('imports OK')"

# ---------------------------------------------------------------------------
# Step 3 — Verify ssh-to-lakehouse works
# ---------------------------------------------------------------------------
echo
echo "=== Step 3: verify ssh to $NAS_REMOTE_USER@$NAS_REMOTE_HOST ==="
if ssh -o BatchMode=yes -o ConnectTimeout=5 \
   "$NAS_REMOTE_USER@$NAS_REMOTE_HOST" "mkdir -p ~/.nexus/incoming/$HOST_ID && echo OK" \
   >/dev/null 2>&1; then
    echo "  ssh + remote ~/.nexus/incoming/$HOST_ID OK"
else
    echo "ERROR: cannot reach $NAS_REMOTE_USER@$NAS_REMOTE_HOST without a password." >&2
    echo "       Run 'ssh-copy-id $NAS_REMOTE_USER@$NAS_REMOTE_HOST' first, then re-run this script." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Step 4 — collect.toml
# ---------------------------------------------------------------------------
echo
echo "=== Step 4: $NEXUS_HOME/collect.toml ==="
mkdir -p "$NEXUS_HOME"/{state,staging}
if [ -f "$NEXUS_HOME/collect.toml" ]; then
    cp "$NEXUS_HOME/collect.toml" "$NEXUS_HOME/collect.toml.bak.$(date +%s)"
    echo "  backed up existing collect.toml"
fi

if [ "$ENABLE_OPENCLAW" = "true" ]; then OPENCLAW_ENABLED="true"; else OPENCLAW_ENABLED="false"; fi
if [ "$ENABLE_TEMPO_RELAY" = "true" ]; then TEMPO_ENABLED="true"; else TEMPO_ENABLED="false"; fi
TEMPO_SERVICES_TOML="[$(echo "$TEMPO_SERVICES" | awk -F',' '{for(i=1;i<=NF;i++){printf "%s\"%s\"", (i>1?", ":""), $i}}')]"

cat > "$NEXUS_HOME/collect.toml" <<EOF
# nexus-collect host config — $HOST_ID (Linux)
# Generated by scripts/install_shipper_linux.sh on $(date -Iseconds).
# Ships to the mac-mini lakehouse via rsync over ssh.

host_id     = "$HOST_ID"
remote_host = "$NAS_REMOTE_HOST"
remote_user = "$NAS_REMOTE_USER"
state_dir   = "$NEXUS_HOME/state"
staging_dir = "$NEXUS_HOME/staging"

# Standard Claude Code projects on this host
[sources.claude_code]
enabled = true
root    = "$HOME/.claude/projects"
agent_id = "$HOST_ID"

# OpenClaw (Nix) sessions — only on the NAS by default
[sources.openclaw]
enabled = $OPENCLAW_ENABLED
root    = "$HOME/.openclaw/agents/main/sessions"

# Sources not on Linux hosts
[sources.claude_macmini]
enabled = false
root    = "$HOME/Library/Application Support/Claude/local-agent-mode-sessions"

[sources.hermes]
enabled = false
root    = "$HOME/.hermes/profiles/jenny/sessions"

[sources.pi_mono]
enabled = false
db_path = "$HOME/max/data/task-journal.db"

# Tempo → OTLP relay (pulls AgentWeave/Mux spans into the lakehouse).
[tempo]
enabled              = $TEMPO_ENABLED
tempo_base           = "$TEMPO_BASE_URL"
services             = $TEMPO_SERVICES_TOML
target_otlp_endpoint = "$TEMPO_TARGET_OTLP"
lookback_seconds     = 60
initial_window_s     = 3600
EOF
echo "  wrote $NEXUS_HOME/collect.toml"
uv run nexus-collect status

# ---------------------------------------------------------------------------
# Step 5 — Render + install systemd user units
# ---------------------------------------------------------------------------
echo
echo "=== Step 5: systemd --user units ==="
SYSTEMD_DIR="$HOME/.config/systemd/user"
mkdir -p "$SYSTEMD_DIR"

sed -e "s|@@REPO_DIR@@|$REPO_DIR|g" \
    -e "s|@@HOME@@|$HOME|g" \
    "$REPO_DIR/scripts/systemd/nexus-collect.service.template" \
    > "$SYSTEMD_DIR/nexus-collect.service"

cp "$REPO_DIR/scripts/systemd/nexus-collect.timer.template" \
   "$SYSTEMD_DIR/nexus-collect.timer"

if [ "$TEMPO_ENABLED" = "true" ]; then
    sed -e "s|@@REPO_DIR@@|$REPO_DIR|g" \
        -e "s|@@HOME@@|$HOME|g" \
        "$REPO_DIR/scripts/systemd/nexus-tempo-relay.service.template" \
        > "$SYSTEMD_DIR/nexus-tempo-relay.service"
    cp "$REPO_DIR/scripts/systemd/nexus-tempo-relay.timer.template" \
       "$SYSTEMD_DIR/nexus-tempo-relay.timer"
    echo "  rendered nexus-tempo-relay units"
fi

systemctl --user daemon-reload
systemctl --user enable --now nexus-collect.timer
if [ "$TEMPO_ENABLED" = "true" ]; then
    systemctl --user enable --now nexus-tempo-relay.timer
fi

# Allow user services to run without an active login
if command -v loginctl >/dev/null 2>&1; then
    loginctl enable-linger "$USER" 2>/dev/null || \
        echo "  (skipped: loginctl enable-linger needs sudo; run manually if shipper stops after logout)"
fi

systemctl --user list-timers nexus-collect.timer --no-pager || true

# ---------------------------------------------------------------------------
# Step 6 — Trigger an immediate ship
# ---------------------------------------------------------------------------
echo
echo "=== Step 6: immediate first ship ==="
systemctl --user start nexus-collect.service
sleep 3
echo "  recent log lines:"
journalctl --user -u nexus-collect -n 20 --no-pager || tail -20 /tmp/nexus-collect.log 2>/dev/null

if [ "$TEMPO_ENABLED" = "true" ]; then
    echo
    echo "=== Step 6b: immediate first tempo-relay tick ==="
    systemctl --user start nexus-tempo-relay.service
    sleep 3
    echo "  recent log lines:"
    journalctl --user -u nexus-tempo-relay -n 20 --no-pager || tail -20 /tmp/nexus-tempo-relay.log 2>/dev/null
fi

# ---------------------------------------------------------------------------
# Step 7 — Verify lakehouse received the ship
# ---------------------------------------------------------------------------
echo
echo "=== Step 7: verify lakehouse received ==="
ssh "$NAS_REMOTE_USER@$NAS_REMOTE_HOST" \
    "ls -lat ~/.nexus/incoming/$HOST_ID/.processed/ 2>/dev/null | head -5 || echo '(not yet ingested — wait for next watcher tick)'"

cat <<EOF

===================================================================
Shipper install complete on $(hostname).

  Timer fires every 5 minutes.
  Inspect:
    systemctl --user status nexus-collect.timer
    journalctl --user -u nexus-collect -f
    cat $NEXUS_HOME/collect.toml

  Full install log: /tmp/nexus-shipper-install.log
===================================================================
EOF
