#!/usr/bin/env bash
# install_shipper_macos.sh — install nexus-collect on a macOS host (defaults
# tuned for the work MacBook), shipping to the mac-mini lakehouse.
#
# Run on the target Mac as your normal user from inside the nexus repo:
#   cd ~/jenny/nexus
#   bash scripts/install_shipper_macos.sh
#
# Idempotent: re-running upgrades the install in place.
#
# Knobs (override via env):
#   HOST_ID        agent_id for this host's claude_code source (default: work-macbook-claude)
#   REMOTE_HOST    ssh target for the lakehouse host (default: Arnabs-Mac-mini.local)
#   REMOTE_USER    user on the lakehouse host       (default: arnabmac)
#   NEXUS_HOME     per-user state dir for the shipper (default: $HOME/.nexus)

set -euo pipefail
exec > >(tee -a /tmp/nexus-shipper-install.log) 2>&1

echo "==================================================================="
echo "Nexus shipper install (macOS/launchd) — $(date -Iseconds)"
echo "==================================================================="

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
NEXUS_HOME="${NEXUS_HOME:-$HOME/.nexus}"
HOST_ID="${HOST_ID:-work-macbook-claude}"
REMOTE_HOST="${REMOTE_HOST:-Arnabs-Mac-mini.local}"
REMOTE_USER="${REMOTE_USER:-arnabmac}"

# Skip the install entirely if you accidentally run this on the lakehouse host.
if [ "$REMOTE_HOST" = "$(hostname).local" ] || [ "$REMOTE_HOST" = "$(hostname)" ]; then
    echo "ERROR: REMOTE_HOST ($REMOTE_HOST) appears to be THIS host." >&2
    echo "       Don't run install_shipper_macos.sh on the lakehouse host itself —" >&2
    echo "       use the local-mode shipper config (remote_host=\"\") instead." >&2
    exit 1
fi

cat <<EOF

REPO_DIR     : $REPO_DIR
NEXUS_HOME   : $NEXUS_HOME
HOST_ID      : $HOST_ID
SHIP TO      : $REMOTE_USER@$REMOTE_HOST:~/.nexus/incoming/$HOST_ID/
EOF

cd "$REPO_DIR"

# ---------------------------------------------------------------------------
# Step 1 — uv
# ---------------------------------------------------------------------------
echo
echo "=== Step 1: uv ==="
if ! command -v uv >/dev/null 2>&1; then
    echo "uv missing — installing via official script"
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
fi
echo "uv version: $(uv --version)"

# ---------------------------------------------------------------------------
# Step 2 — Python deps
# ---------------------------------------------------------------------------
echo
echo "=== Step 2: uv sync ==="
uv sync --quiet
uv run python -c "import click, pydantic; print('imports OK')"

# ---------------------------------------------------------------------------
# Step 3 — Verify ssh-to-lakehouse works
# ---------------------------------------------------------------------------
echo
echo "=== Step 3: verify ssh to $REMOTE_USER@$REMOTE_HOST ==="
if ssh -o BatchMode=yes -o ConnectTimeout=5 \
   "$REMOTE_USER@$REMOTE_HOST" "mkdir -p ~/.nexus/incoming/$HOST_ID && echo OK" \
   >/dev/null 2>&1; then
    echo "  ssh + remote ~/.nexus/incoming/$HOST_ID OK"
else
    echo "ERROR: cannot reach $REMOTE_USER@$REMOTE_HOST without a password." >&2
    echo "       Run 'ssh-copy-id $REMOTE_USER@$REMOTE_HOST' first, then re-run this script." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Step 4 — collect.toml
# ---------------------------------------------------------------------------
echo
echo "=== Step 4: $NEXUS_HOME/collect.toml ==="
mkdir -p "$NEXUS_HOME"/{state,staging}
if [ -f "$NEXUS_HOME/collect.toml" ]; then
    cp "$NEXUS_HOME/collect.toml" "$NEXUS_HOME/collect.toml.bak.$(date +%s)"
    echo "  backed up existing collect.toml"
fi

# Detect which sources actually exist on this Mac so we don't enable empty roots.
LOCAL_AGENT_DIR="$HOME/Library/Application Support/Claude/local-agent-mode-sessions"
HERMES_DIR="$HOME/.hermes/profiles/jenny/sessions"
[ -d "$LOCAL_AGENT_DIR" ] && CLAUDE_MACMINI_ENABLED="true" || CLAUDE_MACMINI_ENABLED="false"
[ -d "$HERMES_DIR" ]      && HERMES_ENABLED="true"        || HERMES_ENABLED="false"

cat > "$NEXUS_HOME/collect.toml" <<EOF
# nexus-collect host config — $HOST_ID (macOS)
# Generated by scripts/install_shipper_macos.sh on $(date -Iseconds).
# Ships to the mac-mini lakehouse via rsync over ssh.

host_id     = "$HOST_ID"
remote_host = "$REMOTE_HOST"
remote_user = "$REMOTE_USER"
state_dir   = "$NEXUS_HOME/state"
staging_dir = "$NEXUS_HOME/staging"

# Standard Claude Code projects on this host
[sources.claude_code]
enabled = true
root    = "$HOME/.claude/projects"
agent_id = "$HOST_ID"

# Claude Desktop's local-agent-mode (only enabled if the dir exists)
[sources.claude_macmini]
enabled = $CLAUDE_MACMINI_ENABLED
root    = "$LOCAL_AGENT_DIR"

# Hermes (only enabled if the dir exists)
[sources.hermes]
enabled = $HERMES_ENABLED
root    = "$HERMES_DIR"

# Sources not on macOS
[sources.openclaw]
enabled = false
root    = "$HOME/.openclaw/agents/main/sessions"

[sources.pi_mono]
enabled = false
db_path = "$HOME/max/data/task-journal.db"
EOF
echo "  wrote $NEXUS_HOME/collect.toml"
uv run nexus-collect status

# ---------------------------------------------------------------------------
# Step 5 — launchd plist
# ---------------------------------------------------------------------------
echo
echo "=== Step 5: launchd plist ==="
PLIST="$HOME/Library/LaunchAgents/com.arnab.nexus-collect.plist"
mkdir -p "$(dirname "$PLIST")"

UV_PATH="$(command -v uv)"
cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.arnab.nexus-collect</string>
    <key>ProgramArguments</key>
    <array>
        <string>$UV_PATH</string>
        <string>run</string>
        <string>--quiet</string>
        <string>nexus-collect</string>
        <string>run</string>
    </array>
    <key>WorkingDirectory</key>
    <string>$REPO_DIR</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>$HOME</string>
        <key>PATH</key>
        <string>$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
    <key>StartInterval</key>
    <integer>300</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/nexus-collect.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/nexus-collect.log</string>
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
EOF
echo "  wrote $PLIST"

launchctl unload "$PLIST" 2>/dev/null || true
launchctl load -w "$PLIST"
launchctl list | grep nexus-collect || echo "  (not loaded — check $PLIST)"

# ---------------------------------------------------------------------------
# Step 6 — Trigger an immediate ship
# ---------------------------------------------------------------------------
echo
echo "=== Step 6: immediate first ship ==="
launchctl start com.arnab.nexus-collect 2>/dev/null || true
sleep 5
echo "  recent log lines:"
tail -15 /tmp/nexus-collect.log 2>/dev/null || echo "  (no log yet — wait a minute and re-check)"

# ---------------------------------------------------------------------------
# Step 7 — Verify lakehouse received
# ---------------------------------------------------------------------------
echo
echo "=== Step 7: verify lakehouse received ==="
ssh "$REMOTE_USER@$REMOTE_HOST" \
    "ls -lat ~/.nexus/incoming/$HOST_ID/.processed/ 2>/dev/null | head -5 || echo '(not yet ingested — wait for next watcher tick)'"

cat <<EOF

===================================================================
Shipper install complete on $(hostname).

  launchd job fires every 5 minutes.
  Inspect:
    launchctl list | grep nexus-collect
    tail -f /tmp/nexus-collect.log
    cat $NEXUS_HOME/collect.toml

  Full install log: /tmp/nexus-shipper-install.log
===================================================================
EOF
